---
openapi: 3.0.0
info:
  title: SEGA - DALI
  description: |
    Para realizar pedidos de los servicios de Chazki, se habilitaron puntos finales 
    para registrar la entrega y verificar el estado de los pedidos. 
    
    Estos servicios están registrados en el dominio propiedad de chazki y se detallan 
    en el apartado siguiente. Descubre más sobre [Chazki aquí](https://chazki.com/#/). 
    Consulte también nuestros [Términos y condiciones](https://www.chazki.com/politica-de-privacidad).
  termsOfService: https://chazki.com/tyc.html
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 2.0.0
servers:
  - url: https://integrations.ng.paquery.com/sega/api/v2/shipment
    description: Sega Production

paths:
  "/create":
    post:
      description: Este endpoint permite registrar un envio.
      operationId: Crear Orden
      parameters:
        - "$ref": '#/components/parameters/queryEnterpriseKey'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/createShipment"
      responses:
        "200":
          "$ref": "#/components/responses/responseCreate200"
        "500":
          "$ref": "#/components/responses/responseCreate500"
  "/tracker/:tracking":
    get:
      description: |
        En este endpoint permite realizar el seguimiento del envio, 
        también el historial de cambios de estado.
      operationId: Tracking Orden
      parameters: 
        - "$ref": '#/components/parameters/queryEnterpriseKey'
        - "$ref": '#/components/parameters/trackingParam'
      responses:
        "200":
          "$ref": "#/components/responses/responseStatus200"
  "/pod/:tracking":
    get:
      description: This API allows us to see all the states the delivery passed group by services.The services group reference the number of attempts made to deliver the delivery.
      operationId: Pod
      parameters:
        - "$ref": '#/components/parameters/queryEnterpriseKey'
      responses:
        "200":
          "$ref": "#/components/responses/responseCreate200"
  "/tag/:tracking":
    get:
      description: |
        Con este endpoint obtiene el listado de etiqueta del envío.
      operationId: Etiqueta (tag)
      parameters:
        - "$ref": '#/components/parameters/queryEnterpriseKey'
      responses:
        "200":
          "$ref": "#/components/responses/responseLabel200"
  "/:tracking":
    get:
      description: This API allows us to see all the states the delivery passed group by services.The services group reference the number of attempts made to deliver the delivery.
      operationId: Tracker
      parameters:
        - "$ref": '#/components/parameters/queryEnterpriseKey'
      responses:
        "200":
          "$ref": "#/components/responses/responseCreate200"

components:
  schemas:
    geoData:
      type: object
      description: Estructura de las coordenadas de la dirección de recojo o entrega.
      properties:
        lat:
          type: number
          description: Coordenadas de la dirección de recojo o entrega (latitud).
          example: -12.0052
        lng:
          type: number
          description: Coordenadas de la dirección de recojo o entrega (longitude).
          example: -90.0034
    address:
      type: object
      description: |
        Estructura con la información de recojo o entrega,
        para la estura 'origen' es posible enviar null si se desea tomar la dirección 
        registrada en el marketplace por defecto.

        **Nota:** En el campo 'line' debe venir la dirección, el número de la calle, localidad/barrio, 
        ciudad, país, código postal. No es obligatorio que venga toda esta información, pero 
        mientras más detalle mayor probabilidad de que sea localizada. Solo datos de dirección, 
        no comentarios acerca de la dirección.
      properties:
        line:
          type: string
          description: Dirección de recojo o entrega de los productos.
          example: XXXXXXXXXXXXXXXXXXXXXXXXX
        zip:
          type: string
          description: Código postal de la dirección para el recojo o entrega de los productos.
          example: "15314"
        route:
          type: string
          description: Nombre de la dirección para el recojo o entrega de los productos.
          example: " "
        streetNumber:
          type: number
          description: Numero de la dirección para el recojo o entrega de los productos.
          example: 0
        locality:
          type: string
          description: Distrito o localidad donde se realiza el recojo o entrega de los productos.
          example: XXXXXXXXXXXXXXXXXXXXXXXXX
        region:
          type: string
          description: (deprecated) Provincia donde se realiza el recojo o entrega de los productos
          example: XXXXXXXXXXXXXXXXXXXXXXXXX
        latLng:
          "$ref": "#/components/schemas/geoData"
      required:
        - line
        - latLng
    origin:
      type: object
      properties:
        name:
          type: string
          description: Nombres de contacto para el recojo o entrega de productos.
          example: XXXXXXXXXXXXXXXXXXXXXXXXX
        phone:
          type: string
          description: Numero de telefono/celular de contacto para el recojo o entrega de productos.
          example: XXXXX-xxxxx
        email:
          type: string
          description: Email para notificación el recojo o entrega de los productos.
          example: mail@mail.com
        reference:
          type: string
          description: Referencias de direcciones de clientes para el recojo o entrega de los productos.
          example: "-"
        notes:
          type: string
          description: Datos adicionales que facilitan la recojo o entrega de productos.
          example: "-"
        schedule:
          type: string
          description: Datos de franja horaria para el recojo o entrega de productos.
          example: "08 a 18"
        address:
          "$ref": "#/components/schemas/address"
      required:
        - name
        - phone
        - email
        - Address
    product:
      type: object
      properties:
        description:
          type: string
          description: Descripción o nombres de los productos de la orden.
          example: "XXXXXXX XXXXXXXXX XXXXXXXX"
        value:
          type: number
          description: |
            Precio o valor de paquetes.
          example: 0
        quantity:
          type: number
          description: |
            Número total de paquetes.
            
            **Nota:** al enviar 0, se crea una sola etiqueta para el envío, de 
            lo contrario se genera una etiqueta según la cantidad de paquetes.
          example: 0
        size:
          type: string
          description: Tamaño promedio de los paquetes.
          example: "Chico"
        dimensions:
          "$ref": "#/components/schemas/dimensions"
      required:
        - description
    dimensions:
      type: object
      properties:
        height:
          type: number
          description: Altura promedio de los paquetes.
          example: 0
        width:
          type: number
          description: Ancho promedio de los paquetes.
          example: 0
        length:
          type: number
          description: Largo promedio de los paquetes.
          example: 0
    shipment:
      type: object
      properties:
        tracking:
          type: string
          description: Código de orden o código de seguimiento, con este código podrás rastrear el pedido.
          example: XXXXX-12345
        type:
          type: string
          description: |
            Código del tipo de servicio de entrega. 
            
            Puede tomar los siguientes valores:

            | Servicio (Todos los países) | Descripción |
            | ------------- | ------------ |
            | NEXT DAY | El pedido se enviará al día siguiente. |
            | SAME DAY | El pedido se enviará el mismo día. |

            **Nota:** Paara el servicio 'NEXT DAY' se tiene una hora limite
            en el cual se realizara la entrega si se recibe antes de la hora 
            límite, en caso contrario se enviará al día siguiente (La hora 
            límite se puede solicitar al área comercial).
          example: "SAME DAY"
        cod:
          type: number
          description: |
            Para el valor 0 (false) es envio se indica como pagado, para el 
            valor 1 (true) el pago se realiza en la dirección de destino 
            (contra reembolso), el importe a cobrar al destinatario final es 
            enviado en el campo value dentro de product.
          example: 0
        change:
          type: bool
          description: |
            Indicador de lógica inversa, nos permite realizar en caso de 
            ser necesario el recojo de ordenes para devolución desde el cliente
            final.
          example: false
        product:
          "$ref": "#/components/schemas/product"
        origin:
          "$ref": "#/components/schemas/origin"
        destination:
          "$ref": "#/components/schemas/origin"
      required:
        - tracking
        - type
        - change
        - product
        - origin
        - destination
    createShipment:
      type: object
      properties:
        shipment:
          "$ref": "#/components/schemas/shipment"
  responses:
    addressResponse:
      type: object
      properties:
        address:
          type: string
          description: Dirección de recojo o entrega de los productos.
          example: "Calle F. Valle Riestra 576, San Isidro, Lima 15074, Perú"
        name:
          type: string
          description: Nombres de contacto para el recojo o entrega de productos.
          example: XXXXXXXXXXXXXXXXXXXXXXXXX
        phone:
          type: string
          description: Numero de telefono/celular de contacto para el recojo o entrega de productos.
          example: XXXXX-xxxxx
        email:
          type: string
          description: Email para notificación el recojo o entrega de los productos.
          example: mail@mail.com
        reference:
          type: string
          description: Referencias de direcciones de clientes para el recojo o entrega de los productos.
          example: "-"
        notes:
          type: string
          description: Datos adicionales que facilitan la recojo o entrega de productos.
          example: "-"
        schedule:
          type: string
          description: Datos de franja horaria para el recojo o entrega de productos.
          example: "08 a 18"
    contactResponse:
      type: object
      properties:
        reference:
          type: string
          description: Referencias de direcciones de clientes para el recojo o entrega de los productos.
          example: "-"
        notes:
          type: string
          description: Datos adicionales que facilitan la recojo o entrega de productos.
          example: "-"
        schedule:
          type: string
          description: Datos de franja horaria para el recojo o entrega de productos. 
          example: "-"
        address:
          type: object
          properties:
            line:
              type: string
              description: Dirección de recojo o entrega de los productos.
              example: XXXXXXXXXXXXXXXXXXXXXXXXX
            latLng:
              "$ref": "#/components/schemas/geoData"
    historyResponse:
      type: object
      properties:
        date:
          type: string
          description: Fecha de evento en formato RFC-3339 (ISO-8601) en UTC.
          example: "2024-06-20T19:05:08Z"
        description:
          type: string
          description: Detalle del evento generado.
          example: "En Chazki"
        location:
          type: string
          description: Localidad o distrito donde se genera el evento.
          example: "Buenos Aires"
    "responseCreate200":
      description: Successfully response object.
      content:
        application/json:
          schema:
            type: object
            properties:
              shipment:
                type: object
                description: Datos recibidos en la creación de ordenes para realizar el envío.
                properties:
                  tracking:
                    type: string
                    description: Código de orden o código de seguimiento, con este código podrás rastrear el pedido.
                    example: XXXXX-12345
                  type:
                    type: string
                    description: |
                      Código del tipo de servicio de entrega. 
                      
                      Puede tomar los siguientes valores:

                      | Servicio (Todos los países) | Descripción |
                      | ------------- | ------------ |
                      | NEXT DAY | El pedido se enviará al día siguiente. |
                      | SAME DAY | El pedido se enviará el mismo día. |

                      **Nota:** Paara el servicio 'NEXT DAY' se tiene una hora limite
                      en el cual se realizara la entrega si se recibe antes de la hora 
                      límite, en caso contrario se enviará al día siguiente (La hora 
                      límite se puede solicitar al área comercial).
                    example: "SAME DAY"
                  #kind:
                  #  type: string
                  #  description: Type of service at a commercial level.
                  #  example: "B2B"
                  change:
                    type: bool
                    description: |
                      Indicador de lógica inversa, nos permite realizar en caso 
                      de ser necesario el recojo de ordenes para devolución desde 
                      el cliente final.
                    example: false
                  product:
                    type: object
                    properties:
                      size:
                        type: string
                        description: Tamaño promedio de los paquetes.
                        example: "Chico"
                      dimensions:
                        "$ref": "#/components/schemas/dimensions"
                  origin:
                    "$ref": "#/components/responses/addressResponse"
                  destination:
                    "$ref": "#/components/responses/addressResponse"
                  status:
                    type: string
                    description: Estado del envío.
                    example: QUEUE
                  created:
                    type: string
                    description: |
                      Fecha de creación en formato RFC-3339 (ISO-8601) en UTC.
                    example: "2024-06-20T18:21:21Z"
                  removed:
                    type: bool
                    description: |
                      Indicador que informa si el pedido se encuentra en 
                      estado cancelado, eliminado y/o anulado.
                    example: false
                  trackingUrl:
                    type: string
                    description: Enlace de seguimiento de pedido.
                    example: "https://tracking.ng.paquery.com/package/MzU1MTM5Ng"
    "responseCreate500":
      description: El error se mostrará en texto simple indicando el motivo.
    "responseStatus200":
      description: Successfully response object.
      content:
        application/json:
          schema:
            type: object
            properties:
              shipment:
                type: object
                description: Datos recibidos en la creación de ordenes para realizar el envío.
                properties:
                  created:
                    type: string
                    description: |
                      Fecha de creación en formato RFC-3339 (ISO-8601) en UTC.
                    example: "2024-06-20T18:21:21Z"
                  tracking:
                    type: string
                    description: Código de orden o código de seguimiento, con este código podrás rastrear el pedido.
                    example: XXXXX-12345
                  type:
                    type: string
                    description: |
                      Código del tipo de servicio de entrega. 
                      
                      Puede tomar los siguientes valores:

                      | Servicio (Todos los países) | Descripción |
                      | ------------- | ------------ |
                      | NEXT DAY | El pedido se enviará al día siguiente. |
                      | SAME DAY | El pedido se enviará el mismo día. |

                      **Nota:** Paara el servicio 'NEXT DAY' se tiene una hora limite
                      en el cual se realizara la entrega si se recibe antes de la hora 
                      límite, en caso contrario se enviará al día siguiente (La hora 
                      límite se puede solicitar al área comercial).
                    example: "SAME DAY"
                  kind:
                    type: string
                    description: Type of service at a commercial level.
                    example: "B2B"
                  company:
                    type: string
                    description: Nombre asociado al marketplace.
                    example: false
                  contact:
                    "$ref": "#/components/responses/contactResponse"
                  history:
                    type: array
                    items: 
                      type: object
                      "$ref": "#/components/responses/historyResponse"
                  updatable:
                    type: bool
                    description: Indica si es posible actualizar los datos de la orden.
                    example: false
                  trackingUrl:
                    type: string
                    description: Enlace de seguimiento de pedido.
                    example: "https://tracking.ng.paquery.com/package/MzU1MTM5Ng"
    "responseLabel200":
      description: |
        Se obtiene un archivo pdf con las etiquetas 
        que se visualiza en el mismo navegador.
  parameters:
    queryEnterpriseKey:
      name: key
      in: query
      description: |
        Identificador de empresa, es un hash generado 
        por Chazki para identificar la empresa, se 
        obtiene una vez generada la empresa dentro de 
        Chazki por el área comercial.
      required: true
      style: form
      explode: false
      schema:
        type: string
    trackingParam:
      name: tracking
      in: path
      description: |
        Código de orden o código de seguimiento
      required: true
      schema:
        type: string
