---
openapi: 3.0.0
info:
  title: SEGA - DALI
  description: |
    Para realizar pedidos de los servicios de Chazki, se habilitaron puntos finales 
    para registrar la entrega y verificar el estado de los pedidos. 
    
    Estos servicios están registrados en el dominio propiedad de chazki y se detallan 
    en el apartado siguiente. Descubre más sobre [Chazki aquí](https://chazki.com/#/). 
    Consulte también nuestros [Términos y condiciones](https://www.chazki.com/politica-de-privacidad).
  termsOfService: https://chazki.com/tyc.html
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 2.0.0
servers:
  - url: https://integrations.ng.paquery.com/sega/api/v2/shipment
    description: Sega Production

paths:
  "/create":
    post:
      description: Este endpoint permite registrar un envio.
      operationId: Crear Orden
      parameters:
        - "$ref": '#/components/parameters/queryEnterpriseKey'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/createShipment"
      responses:
        "200":
          "$ref": "#/components/responses/responseCreate200"
        "500":
          "$ref": "#/components/responses/responseCreate500"
  "/:tracking":
    get:
      description: This API allows us to see all the states the delivery passed group by services.The services group reference the number of attempts made to deliver the delivery.
      operationId: Tracking Order
      parameters:
        - "$ref": '#/components/parameters/queryEnterpriseKey'
      responses:
        "200":
          "$ref": "#/components/responses/responseCreate200"
  "/pod/:tracking":
    get:
      description: This API allows us to see all the states the delivery passed group by services.The services group reference the number of attempts made to deliver the delivery.
      operationId: Pod
      parameters:
        - "$ref": '#/components/parameters/queryEnterpriseKey'
      responses:
        "200":
          "$ref": "#/components/responses/responseCreate200"
  "/tracker/:tracking":
    get:
      description: This API allows us to see all the states the delivery passed group by services.The services group reference the number of attempts made to deliver the delivery.
      operationId: Tracker
      parameters:
        - "$ref": '#/components/parameters/queryEnterpriseKey'
      responses:
        "200":
          "$ref": "#/components/responses/responseCreate200"
  "/tag/:tracking":
    get:
      description: This API allows us to see all the states the delivery passed group by services.The services group reference the number of attempts made to deliver the delivery.
      operationId: Tag Tracking
      parameters:
        - "$ref": '#/components/parameters/queryEnterpriseKey'
      responses:
        "200":
          "$ref": "#/components/responses/uploadOrdersResponse200"

components:
  schemas:
    geoData:
      type: object
      description: Estructura de las coordenadas de la dirección de recojo o entrega.
      properties:
        lat:
          type: number
          description: Coordenadas de la dirección de recojo o entrega (latitud).
          example: -12.0052
        lng:
          type: number
          description: Coordenadas de la dirección de recojo o entrega (longitude).
          example: -90.0034
    address:
      type: object
      description: |
        Estructura con la información de recojo o entrega,
        para la estura 'origen' es posible enviar null si se desea tomar la dirección 
        registrada en el marketplace por defecto.

        *Nota:* En el campo 'line' debe venir la dirección, el número de la calle, localidad/barrio, 
        ciudad, país, código postal. No es obligatorio que venga toda esta información, pero 
        mientras más detalle mayor probabilidad de que sea localizada. Solo datos de dirección, 
        no comentarios acerca de la dirección.
      properties:
        line:
          type: string
          description: Dirección de recojo o entrega de los productos.
          example: XXXXXXXXXXXXXXXXXXXXXXXXX
        zip:
          type: string
          description: Código postal de la dirección para el recojo o entrega de los productos.
          example: "15314"
        route:
          type: string
          description: Nombre de la dirección para el recojo o entrega de los productos.
          example: " "
        streetNumber:
          type: number
          description: Numero de la dirección para el recojo o entrega de los productos.
          example: 0
        locality:
          type: string
          description: Distrito o localidad donde se realiza el recojo o entrega de los productos.
          example: XXXXXXXXXXXXXXXXXXXXXXXXX
        region:
          type: string
          description: (deprecated) Provincia donde se realiza el recojo o entrega de los productos
          example: XXXXXXXXXXXXXXXXXXXXXXXXX
        latLng:
          "$ref": "#/components/schemas/geoData"
      required:
        - line
        - latLng
    origin:
      type: object
      properties:
        name:
          type: string
          description: Nombres de contacto para el recojo o entrega de productos.
          example: XXXXXXXXXXXXXXXXXXXXXXXXX
        phone:
          type: string
          description: Numero de telefono/celular de contacto para el recojo o entrega de productos.
          example: XXXXX-xxxxx
        email:
          type: string
          description: Email para notificación el recojo o entrega de los productos.
          example: mail@mail.com
        reference:
          type: string
          description: Referencias de direcciones de clientes para el recojo o entrega de los productos.
          example: "-"
        notes:
          type: string
          description: Datos adicionales que facilitan la recojo o entrega de productos.
          example: "-"
        schedule:
          type: string
          description: Datos de franja horaria para el recojo o entrega de productos.
          example: "08 a 18"
        address:
          "$ref": "#/components/schemas/address"
      required:
        - name
        - phone
        - email
        - Address
    product:
      type: object
      properties:
        description:
          type: string
          description: Descripción o nombres de los productos de la orden.
          example: "XXXXXXX XXXXXXXXX XXXXXXXX"
        value:
          type: number
          description: |
            Precio o valor de paquetes.
          example: 0
        quantity:
          type: number
          description: |
            Número total de paquetes.
            
            *Nota:* al enviar 0, se crea una sola etiqueta para el envío, de 
            lo contrario se genera una etiqueta según la cantidad de paquetes.
          example: 0
        size:
          type: string
          description: Tamaño promedio de los paquetes.
          example: "Chico"
        dimensions:
          "$ref": "#/components/schemas/dimensions"
      required:
        - description
    dimensions:
      type: object
      properties:
        height:
          type: number
          description: Altura promedio de los paquetes.
          example: 0
        width:
          type: number
          description: Ancho promedio de los paquetes.
          example: 0
        length:
          type: number
          description: Largo promedio de los paquetes.
          example: 0
    shipment:
      type: object
      properties:
        tracking:
          type: string
          description: Código de orden o código de seguimiento, con este código podrás rastrear el pedido.
          example: XXXXX-12345
        type:
          type: string
          description: |
            Se realizará el código del tipo de servicio de entrega. Puede tomar los siguientes valores:

            | Servicio (Todos los países) | Descripción |
            | ------------- | ------------ |
            | NEXT DAY | El pedido se enviará al día siguiente. |
            | SAME DAY | El pedido se enviará el mismo día si se 
            recibe antes de la hora límite, en caso contrario se 
            enviará al día siguiente (La hora límite se puede 
            solicitar al área comercial) |
          example: "SAME DAY"
        cod:
          type: number
          description: Payment is made at the destination address (cash on delivery), the amount to be charged to the final recipient is indicated in the shipmentPrice field.
          example: 0
        change:
          type: bool
          description: Indicador de lógica inversa, nos permite realizar en caso de ser necesario la recogida de pedidos devueltos por el cliente.
          example: false
        product:
          "$ref": "#/components/schemas/product"
        origin:
          "$ref": "#/components/schemas/origin"
        destination:
          "$ref": "#/components/schemas/origin"
      required:
        - tracking
        - type
        - change
        - product
        - origin
        - destination
    createShipment:
      type: object
      properties:
        shipment:
          "$ref": "#/components/schemas/shipment"
  responses:
    addressResponse:
      type: object
      properties:
        address:
          type: string
          description: Address of the client or address of collection of the products.
          example: "Calle F. Valle Riestra 576, San Isidro, Lima 15074, Perú"
        name:
          type: string
          description: Contact Names for the recollection.
          example: XXXXXXXXXXXXXXXXXXXXXXXXX
        phone:
          type: string
          description: Contact phone number for the recollection.
          example: XXXXX-xxxxx
        email:
          type: string
          description: Email for recollection notification.
          example: mail@mail.com
        reference:
          type: string
          description: References of customer addresses or collection of products.
          example: "-"
        notes:
          type: string
          description: Additional data that facilitate the collection of products.
          example: "-"
        schedule:
          type: string
          description: time slot data for collection.
          example: "08 a 18"
    "responseCreate200":
      description: Successfully response object.
      content:
        application/json:
          schema:
            type: object
            properties:
              shipment:
                type: object
                description: Data received in the creation of orders to carry out the shipment.
                properties:
                  tracking:
                    type: string
                    description: Order code or tracking code, with this code you can track the order.
                    example: XXXXX-12345
                  type:
                    type: string
                    description: |
                      Code of the delivery service type will be carried out. It can take the following values :

                      | Service (All the countries) | Description |
                      | ------------- | ------------ |
                      | REGULAR | The order will be sent on the scheduled day according to the customer's configuration. |
                      | NEXT DAY | The order will be shipped the next day. |
                      | SAME DAY | The order will be sent on the same day if it is received before the cut-off time, otherwise it will be sent the next day (The cut-off time can be requested from the commercial area) |
                    example: "SAME DAY"
                  #kind:
                  #  type: string
                  #  description: Type of service at a commercial level.
                  #  example: "B2B"
                  change:
                    type: bool
                    description: Reverse logic indicator, which allows us to collect orders returned by the customer if necessary.
                    example: false
                  product:
                    type: object
                    properties:
                      size:
                        type: string
                        description: total number of packages (when sending 0, a single label is created for the shipment, otherwise a label is generated for each package).
                        example: "Chico"
                      dimensions:
                        "$ref": "#/components/schemas/dimensions"
                  origin:
                    "$ref": "#/components/responses/addressResponse"
                  destination:
                    "$ref": "#/components/responses/addressResponse"
                  status:
                    type: string
                    description: Delivery status.
                    example: QUEUE
                  created:
                    type: string
                    description: Creation date in RFC-3339 (ISO-8601) format in UTC.
                    example: "2024-06-20T18:21:21Z"
                  removed:
                    type: bool
                    description: Indicator that informs whether the order is in cancelled, deleted and/or voided status.
                    example: false
                  trackingUrl:
                    type: string
                    description: Order tracking link.
                    example: "https://tracking.ng.paquery.com/package/MzU1MTM5Ng"
    "responseCreate500":
      description: The error will be displayed in plain text indicating the reason..
  parameters:
    queryEnterpriseKey:
      name: key
      in: query
      description: |
        Company identifier, it is a hash generated by Chazki to
        identify the company, it is obtained once the company has
        been generated within Chazki by the commercial area.
      required: true
      style: form
      explode: false
      schema:
        type: string
