---
openapi: 3.0.0
info:
  title: SEGA - DALI
  description: |
    In order to place orders for Chazki's services, endpoints were enabled to record the delivery and check the orders status. These services are registered in the domain owned by chazki and are detailed in the section below.
    Find out more about [Chazki here](https://chazki.com/#/).
    See also our
  termsOfService: https://chazki.com/tyc.html
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 2.0.0
servers:
  - url: https://integrations.ng.paquery.com/sega/api/v2/shipment
    description: Sega Production

paths:
  "/create":
    post:
      description: This endpoint allows to register a delivery.
      operationId: Create Order 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              shipment:
                type: object
                properties:
                  "$ref": "#/components/schemas/shipment"
      responses:
        "200":
          "$ref": "#/components/responses/responseCreate200"
  "/:tracking":
    get:
      description: This API allows us to see all the states the delivery passed group by services.The services group reference the number of attempts made to deliver the delivery.
      operationId: Tracking Order
      responses:
        "200":
          "$ref": "#/components/responses/responseCreate200"
  "/pod/:tracking":
    get:
      description: This API allows us to see all the states the delivery passed group by services.The services group reference the number of attempts made to deliver the delivery.
      operationId: Pod
      responses:
        "200":
          "$ref": "#/components/responses/responseCreate200"
  "/tracker/:tracking":
    get:
      description: This API allows us to see all the states the delivery passed group by services.The services group reference the number of attempts made to deliver the delivery.
      operationId: Tracker
      responses:
        "200":
          "$ref": "#/components/responses/responseCreate200"
  "/tag/:tracking":
    get:
      description: This API allows us to see all the states the delivery passed group by services.The services group reference the number of attempts made to deliver the delivery.
      operationId: Tag Tracking
      responses:
        "200":
          "$ref": "#/components/responses/uploadOrdersResponse200"

components:
  schemas:
    geoData:
      type: object
      properties:
        lat:
          type: number
          description: Coordinates of picking address (latitude).
          example: -12.0052
        lng:
          type: number
          description: Coordinates of picking address (longitude).
          example: -90.0034
    address:
      type: object
      description: It is possible to send null when it belongs to the origin structure and you want to take the address registered in the marketplace by default.
      properties:
        line:
          type: string
          description: Address of the client or address of collection of the products.
          example: XXXXXXXXXXXXXXXXXXXXXXXXX
        zip:
          type: string
          description: Postal code of the address where the products are picked up.
          example: "15314"
        route:
          type: string
          description: Address of the client or address of collection of the products.
          example: " "
        streetNumber:
          type: number
          description: Avenue number of the client of collection of the products.
          example: 0
        locality:
          type: string
          description: District of address of the client or collection of products.
          example: XXXXXXXXXXXXXXXXXXXXXXXXX
        region:
          type: string
          description: (deprecated) Province of address of the client or collection of products.
          example: XXXXXXXXXXXXXXXXXXXXXXXXX
        latLng:
          "$ref": "#/components/schemas/geoData"
      required:
        - line
        - zip
        - streetNumber
        - latLng
    origin:
      type: object
      properties:
        name:
          type: string
          description: Contact Names for the recollection.
          example: XXXXXXXXXXXXXXXXXXXXXXXXX
        phone:
          type: string
          description: Contact phone number for the recollection.
          example: XXXXX-xxxxx
        email:
          type: string
          description: Email for recollection notification.
          example: mail@mail.com
        reference:
          type: string
          description: References of customer addresses or collection of products.
          example: "-"
        notes:
          type: string
          description: Additional data that facilitate the collection of products.
          example: "-"
        schedule:
          type: string
          description: time slot data for collection.
          example: "08 a 18"
        address:
          "$ref": "#/components/schemas/address"
      required:
        - name
        - phone
        - email
        - reference
        - notes
        - schedule
        - Address
    product:
      type: object
      properties:
        description:
          type: string
          description: Description or names of the products for collection.
          example: "XXXXXXX XXXXXXXXX XXXXXXXX"
        value:
          type: number
          description: total number of packages (when sending 0, a single label is created for the shipment, otherwise a label is generated for each package).
          example: 0
        quantity:
          type: number
          description: total number of packages (when sending 0, a single label is created for the shipment, otherwise a label is generated for each package).
          example: 0
        size:
          type: string
          description: total number of packages (when sending 0, a single label is created for the shipment, otherwise a label is generated for each package).
          example: "Chico"
        dimensions:
          "$ref": "#/components/schemas/dimensions"
      required:
        - description
        - value
        - quantity
    dimensions:
      type: object
      properties:
        height:
          type: number
          description: Average package height.
          example: 0
        width:
          type: number
          description: Average package width.
          example: 0
        length:
          type: number
          description: Average package length.
          example: 0
    shipment:
      type: object
      properties:
        tracking:
          type: string
          description: Order code or tracking code, with this code you can track the order.
          example: XXXXX-12345
        type:
          type: string
          description: |
            Code of the delivery service type will be carried out. It can take the following values :

            | Service (All the countries) | Description |
            | ------------- | ------------ |
            | REGULAR | The order will be sent on the scheduled day according to the customer's configuration. |
            | NEXT DAY | The order will be shipped the next day. |
            | SAME DAY | The order will be sent on the same day if it is received before the cut-off time, otherwise it will be sent the next day (The cut-off time can be requested from the commercial area) |
          example: "SAME DAY"
        cod:
          type: number
          description: Payment is made at the destination address (cash on delivery), the amount to be charged to the final recipient is indicated in the shipmentPrice field.
          example: 0
        change:
          type: bool
          description: Indicador de lógica inversa, nos permite realizar en caso de ser necesario la recogida de pedidos devueltos por el cliente.
          example: false
        product:
          "$ref": "#/components/schemas/product"
        origin:
          "$ref": "#/components/schemas/origin"
        destination:
          "$ref": "#/components/schemas/origin"
      required:
        - tracking
        - type
        - cod
        - change
        - product
        - origin
        - destination
    createShipment:
      type: object
      properties:
        shipment:
          "$ref": "#/components/schemas/shipment"
  responses:
    responseCreate200:
      description: Successfully response object.
        content:
          application/json:
            schema:
              type: object
              properties:
                success:
                  type: boolean
                  description: Indicates if the success is correct.
                  example: true
                ordersWithErrors:
                  description: Number of orders with errors.
                  type: number
                  example: 0
                ordersWithoutErrors:
                  description: Number of orders without error.
                  type: number
                  example: 1
                errorsDetails:
                  description: Brief description of the errors found in the orders..
                  type: array